//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marathon.Kittyhawk.Common.IBEXBus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mpc.com/endeavour/InventoryReceiptShipment", ConfigurationName="IBEXBus.InventoryReceiptShipment_Async_Out")]
    public interface InventoryReceiptShipment_Async_Out {
        
        // CODEGEN: Generating message contract since the operation InventoryReceiptShipment_Async_Out is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sap.com/xi/WebService/soap1.1")]
        void InventoryReceiptShipment_Async_Out(Marathon.Kittyhawk.Common.IBEXBus.InventoryReceiptShipment_Async_Out1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sap.com/xi/WebService/soap1.1")]
        System.Threading.Tasks.Task InventoryReceiptShipment_Async_OutAsync(Marathon.Kittyhawk.Common.IBEXBus.InventoryReceiptShipment_Async_Out1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InventoryReceiptShipment_Async_Out1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mpc.com/sdpt/kittyhawk/2012/01/01/IBEXTransaction", Order=0)]
        public System.Collections.Generic.List<Marathon.Kittyhawk.Services.DataContracts.IBEXTransaction> ArrayOfIBEXTransaction;
        
        public InventoryReceiptShipment_Async_Out1() {
        }
        
        public InventoryReceiptShipment_Async_Out1(System.Collections.Generic.List<Marathon.Kittyhawk.Services.DataContracts.IBEXTransaction> ArrayOfIBEXTransaction) {
            this.ArrayOfIBEXTransaction = ArrayOfIBEXTransaction;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InventoryReceiptShipment_Async_OutChannel : Marathon.Kittyhawk.Common.IBEXBus.InventoryReceiptShipment_Async_Out, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InventoryReceiptShipment_Async_OutClient : System.ServiceModel.ClientBase<Marathon.Kittyhawk.Common.IBEXBus.InventoryReceiptShipment_Async_Out>, Marathon.Kittyhawk.Common.IBEXBus.InventoryReceiptShipment_Async_Out {
        
        public InventoryReceiptShipment_Async_OutClient() {
        }
        
        public InventoryReceiptShipment_Async_OutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InventoryReceiptShipment_Async_OutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryReceiptShipment_Async_OutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventoryReceiptShipment_Async_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Marathon.Kittyhawk.Common.IBEXBus.InventoryReceiptShipment_Async_Out.InventoryReceiptShipment_Async_Out(Marathon.Kittyhawk.Common.IBEXBus.InventoryReceiptShipment_Async_Out1 request) {
            base.Channel.InventoryReceiptShipment_Async_Out(request);
        }
        
        public void InventoryReceiptShipment_Async_Out(System.Collections.Generic.List<Marathon.Kittyhawk.Services.DataContracts.IBEXTransaction> ArrayOfIBEXTransaction) {
            Marathon.Kittyhawk.Common.IBEXBus.InventoryReceiptShipment_Async_Out1 inValue = new Marathon.Kittyhawk.Common.IBEXBus.InventoryReceiptShipment_Async_Out1();
            inValue.ArrayOfIBEXTransaction = ArrayOfIBEXTransaction;
            ((Marathon.Kittyhawk.Common.IBEXBus.InventoryReceiptShipment_Async_Out)(this)).InventoryReceiptShipment_Async_Out(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task Marathon.Kittyhawk.Common.IBEXBus.InventoryReceiptShipment_Async_Out.InventoryReceiptShipment_Async_OutAsync(Marathon.Kittyhawk.Common.IBEXBus.InventoryReceiptShipment_Async_Out1 request) {
            return base.Channel.InventoryReceiptShipment_Async_OutAsync(request);
        }
        
        public System.Threading.Tasks.Task InventoryReceiptShipment_Async_OutAsync(System.Collections.Generic.List<Marathon.Kittyhawk.Services.DataContracts.IBEXTransaction> ArrayOfIBEXTransaction) {
            Marathon.Kittyhawk.Common.IBEXBus.InventoryReceiptShipment_Async_Out1 inValue = new Marathon.Kittyhawk.Common.IBEXBus.InventoryReceiptShipment_Async_Out1();
            inValue.ArrayOfIBEXTransaction = ArrayOfIBEXTransaction;
            return ((Marathon.Kittyhawk.Common.IBEXBus.InventoryReceiptShipment_Async_Out)(this)).InventoryReceiptShipment_Async_OutAsync(inValue);
        }
    }
}
