//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marathon.Kittyhawk.Common.InventoryBus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mpc.com/endeavour/TankInv_3rdPartyKHtoSRA", ConfigurationName="InventoryBus.KHInventory_Async_Out")]
    public interface KHInventory_Async_Out {
        
        // CODEGEN: Generating message contract since the operation KHInventory_Async_Out is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sap.com/xi/WebService/soap1.1")]
        void KHInventory_Async_Out(Marathon.Kittyhawk.Common.InventoryBus.KHInventory_Async_Out1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://sap.com/xi/WebService/soap1.1")]
        System.Threading.Tasks.Task KHInventory_Async_OutAsync(Marathon.Kittyhawk.Common.InventoryBus.KHInventory_Async_Out1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KHInventory_Async_Out1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://mpc.com/sdpt/kittyhawk/2012/01/01/Inventory", Order=0)]
        public System.Collections.Generic.List<Marathon.Kittyhawk.Services.DataContracts.Inventory> ArrayOfInventory;
        
        public KHInventory_Async_Out1() {
        }
        
        public KHInventory_Async_Out1(System.Collections.Generic.List<Marathon.Kittyhawk.Services.DataContracts.Inventory> ArrayOfInventory) {
            this.ArrayOfInventory = ArrayOfInventory;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KHInventory_Async_OutChannel : Marathon.Kittyhawk.Common.InventoryBus.KHInventory_Async_Out, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KHInventory_Async_OutClient : System.ServiceModel.ClientBase<Marathon.Kittyhawk.Common.InventoryBus.KHInventory_Async_Out>, Marathon.Kittyhawk.Common.InventoryBus.KHInventory_Async_Out {
        
        public KHInventory_Async_OutClient() {
        }
        
        public KHInventory_Async_OutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KHInventory_Async_OutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KHInventory_Async_OutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KHInventory_Async_OutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Marathon.Kittyhawk.Common.InventoryBus.KHInventory_Async_Out.KHInventory_Async_Out(Marathon.Kittyhawk.Common.InventoryBus.KHInventory_Async_Out1 request) {
            base.Channel.KHInventory_Async_Out(request);
        }
        
        public void KHInventory_Async_Out(System.Collections.Generic.List<Marathon.Kittyhawk.Services.DataContracts.Inventory> ArrayOfInventory) {
            Marathon.Kittyhawk.Common.InventoryBus.KHInventory_Async_Out1 inValue = new Marathon.Kittyhawk.Common.InventoryBus.KHInventory_Async_Out1();
            inValue.ArrayOfInventory = ArrayOfInventory;
            ((Marathon.Kittyhawk.Common.InventoryBus.KHInventory_Async_Out)(this)).KHInventory_Async_Out(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task Marathon.Kittyhawk.Common.InventoryBus.KHInventory_Async_Out.KHInventory_Async_OutAsync(Marathon.Kittyhawk.Common.InventoryBus.KHInventory_Async_Out1 request) {
            return base.Channel.KHInventory_Async_OutAsync(request);
        }
        
        public System.Threading.Tasks.Task KHInventory_Async_OutAsync(System.Collections.Generic.List<Marathon.Kittyhawk.Services.DataContracts.Inventory> ArrayOfInventory) {
            Marathon.Kittyhawk.Common.InventoryBus.KHInventory_Async_Out1 inValue = new Marathon.Kittyhawk.Common.InventoryBus.KHInventory_Async_Out1();
            inValue.ArrayOfInventory = ArrayOfInventory;
            return ((Marathon.Kittyhawk.Common.InventoryBus.KHInventory_Async_Out)(this)).KHInventory_Async_OutAsync(inValue);
        }
    }
}
